### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [cciuenf/command_line_intro#38]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by zoedsoupe** [comment]
Boa noite! Desculpe a demora, acabei não recebendo notificação desse repositório!

Sim, este projeto se encontra ativo, porém sem previsão de data para a próxima edição.

Mas sim, aceitamos sempre contribuições!

**Comment by zoedsoupe** [comment]
Perfeito então! Sinta-se a vontade para contribuir!
