### ISSUE TITLE
site

### ISSUE THREAD

**Issue by ghost** [cciuenf/command_line_intro#39]
Oi pessoal.

*introdução*
Ultimamente li muito sobre a questão de dados abertos e conhecimento aberto, e sinto que essa ideia poderia contribuir de alguma forma para essas duas questões.

*ideia*
Minha ideia inicialmente seria transformar esse repositório em uma documentação pública online e acessível através do GitHub Pages. Acredito com isso podemos avaliar melhor o conhecimento que temos e também produzir certos dados de análise sobre isso. De certa forma, como falei na introdução pode envolver a ideia de dados abertos e conhecimento aberto.

*problema geral*
Mas o único problema que vejo com essa ideia é que o arquivo deve ser escrito em markdown e não em org-mode, já que o framework que tenho conhecimento para tornar possível essa ideia só seria possível com isso. Esse framework que conheço gera sites, páginas em html e documentação técnica com arquivos markdown.

*demonstração*
Vamos supor que alguém acesse essa url: `https://introducaolinhadecomando.github.io/`

nesse caso teria como possibilidade isso:
![image](https://user-images.githubusercontent.com/111701513/212572292-3ee539f8-5e2c-4b27-b54d-c53065ee6f36.png)

*feedback*
O que você pensam dessa ideia? seria interessante ou ao menos viável?

**Comment by zoedsoupe** [comment]
Boa ideia! Qual seria o framework? Imagino que o gatsby, certo? Não vejo problemas de escrevermos em markdown, o emacs até permite exportar org-mode para markdown nativamente, então não geraria um grande retrabalho...

Tenho interesse sim nessa possibilidade. Na verdade eu gostaria de expandir para ser como um minicurso gameficado, porém essa ideia ainda tá sendo amadurecida.

**Comment by zoedsoupe** [comment]
Perfeito então! Podemos começar com essa ideia inicial com o `docsify` e vou tentar amadurecer essa ideia do minicurso! Aceito sugestões e novas ideias de como prosseguir com a gameficação (:

**Comment by zoedsoupe** [comment]
Estou de acordo! Fico feliz em ver interesse no projeto, obrigada!

**Comment by zoedsoupe** [comment]
Estou de acordo! Fico feliz em ver interesse no projeto, obrigada!
